apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo-app
  namespace: foo
  labels:
    app: foo-app
spec:
  selector:
    matchLabels:
      app: foo-app
  template:
    metadata:
      labels:
        app: foo-app
    spec:
      serviceAccountName: foo-runner
      containers:
      - name: foo
        image: ko://github.com/yolocs/foo-app/cmd/foo
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: foo-app
  namespace: foo
spec:
  selector:
    app: foo-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080